---
global:
  indexerConfig:
    metricsDirectory: /Users/anjoseph/labs/kube-burner-metrics
    createTarball: true
    type: local
  measurements:
    - name: pprof
      pprofInterval: 3m
      pprofDirectory: /Users/anjoseph/labs/kube-burner-metrics/pprof-data
      pprofTargets:
        - name: openshift-gitops-server
          namespace: "openshift-gitops"
          labelSelector: {app.kubernetes.io/name: openshift-gitops-server}
          url: http://localhost:8083/debug/pprof/heap
        - name: openshift-gitops-server
          namespace: "openshift-gitops"
          labelSelector: {app.kubernetes.io/name: openshift-gitops-server}
          url: http://localhost:8083/debug/pprof/goroutine
jobs:
  - name: create-argo-applications
    jobIterations: 50
    qps: 20
    burst: 20
    namespacedIterations: true
    namespace: argo-cd-app-ns
    waitWhenFinished: true
    podWait: false
    objects:
      - objectTemplate: templates/argo-application.yaml
        replicas: 1
  - name: patch-argocd
    jobIterations: 50
    jobType: patch
    qps: 20
    burst: 20
    namespacedIterations: false
    namespace: default
    waitWhenFinished: true
    objects:
      - kind: ArgoCD 
        apiVersion: argoproj.io/v1alpha1
        labelSelector: {kube-burner-job: create-argo-applications}
        objectTemplate: templates/argocd_patch.yaml
        patchType: "application/apply-patch+yaml"