apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble-animation-app-{{.Iteration}}
spec:
  destination:
    namespace: argo-cd-app-ns-{{.Iteration}}
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: bubble-animation/application-mainfest
    repoURL: https://github.com/akram/argocd-openshift
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true

